### ISSUE TITLE
Slow accepting

### ISSUE THREAD

**Issue by haimiyahya** [mtrudel/thousand_island#100]
Hi,

This is not a bug, more to a question, however I don't know where else to ask.

I created an application that listen to a port.

```elixir
defmodule MyApp.ConnectionHandler do

  use ThousandIsland.Handler

  @impl ThousandIsland.Connection
  def handle_connection(socket, state) do

    IO.inspect "new client connected"

    {:close, state}
  end

  @impl ThousandIsland.Handler
  def handle_data(data, socket, state) do
    {:continue, state}
  end
end


```

Notice I disconnects immediately to enable me to measure the TCP accept timespan.

```elixir
defmodule Test1.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  @impl true
  def start(_type, _args) do
    children = [
      {ThousandIsland, port: 11234, handler_module: MyApp.ConnectionHandler},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Test1.Supervisor]
    Supervisor.start_link(children, opts)
  end
end
```

Then I write a simple bat file

```cmd

ECHO:| TIME >> measure_time__.txt
telnet localhost 11234
ECHO:| TIME >> measure_time__.txt

```

Then I run the bat file.

```batch
measure_connect.bat
```

Then I got this result

```batch

The current time is: 12:28:11.24
Enter the new time: 
The current time is: 12:28:13.51
Enter the new time: 

```

The result summarize that it takes about 2 seconds to just accept then disconnects, is that normal? 
Is there anything that I can do to make it accept the connection faster? 
Is this just happening on Window only?

Thank you,

-- Haimi

**Comment by mtrudel** [comment]
Issue 100!

You're correct that this should return nearly immediately. A local test on macOS:

```elixir
✓[mat@lappy ~/Code/thousand_island] (main)$ time nc localhost 4000
nc localhost 4000  0.00s user 0.00s system 53% cpu 0.012 total
```

so I'm fairly confident that it's not your code. I'm also not too up to date on the state of Windows, but some ideas:

* I think `TIME` asks you to provide a new time (you can see this is in your log above). This will add a relatively enormous amount to your timing, waiting for you to hit enter
* Is it possible that localhost resolution is slower than expected? Do you get this with 127.0.0.1?
* Otherwise, Thousand Island is just a very thin wrapper on top of gen_tcp, and any options supported there are transparently supported by Thousand Island as well. Perhaps dig around in the [gen_tcp documentation](https://www.erlang.org/doc/man/gen_tcp.html) to see if anything interesting pops up with respect to Windows options?
*

**Comment by mtrudel** [comment]
Closing for hygiene. If you feel there continues to be an issue warranting future discussion, feel free to reopen this issue.
