### ISSUE TITLE
Using the ThousandIsland.Handler "escape hatch"

### ISSUE THREAD

**Issue by sthompson-crestron** [mtrudel/thousand_island#118]
I am using `:thousand_island` from hex as {:thousand_island, "~>1.3.5"}. 
According to mix.lock I do have 1.3.5.

I am trying to use ThousandIsland to handle a proprietary TCP protocol.  I am trying to replicate some existing code (written for another environment) which reads the header for a message (the header includes a payload length), then reads the body of the message  using that length.   Most of the time those should come in as a single TCP transmission (and would therefore be a single call to `ThousandIsland.Handler.handle_data` I assume.)  

But (based on this existing code) that also might not be true in all cases.  I believe that might lead to a single message which would span multiple calls to `handle_data`.

I thought I would solve the problem by using the info under "When Handler Isn't Enough" in the documentation, and read the data using two `recv` calls, directly on the socket.  To that end I have created a GenServer that handles the `:thousand_island_ready` message according to the documentation:

```elixir

  defmodule MyApp.ProtocolHandler do

  ...

  @impl GenServer
  def handle_info(
        {:thousand_island_ready, socket, _server_config, _acceptor_span, _start_time},
        %{ handler: packet_handler }
      ) do

    {:ok, socket} = ThousandIsland.Socket.handshake(socket)

  ...
```

The problem is that the "socket" parameter I am receiving as part of handling that message is `#Port<0.4>` and not a `ThousandIsland.Socket` struct.  Consequently the call to `handshake` fails  with

```
** (FunctionClauseError) no function clause matching in ThousandIsland.Socket.handshake/1
```

So it appears that the process sending the `:thousand_island_ready` tuple is sending the raw socket instead of a `ThousandIsland.Socket` to wrap it.  I suspect this is a bug, but it could also be a problem with the documentation.

(P.S.  Just as a point of interest, I had this code working though `:ranch` in a similar fashion.  I am trying to adopt ThousandIsland primarily as a learning experience).

**Comment by mtrudel** [comment]
Yep, that's a bug in the 'When handler isn't enough' documentation. The socket that gets passed there is in fact the raw transport socket and not a wrapped `ThousandIsland.Socket` struct. This is intentional; the reason being that the [caller of this](https://github.com/mtrudel/thousand_island/blob/76c6e1c521bcd77b2e04b40d1d9d1151571f7315/lib/thousand_island/connection.ex#L61-L61) is the acceptor process, and it needs to do as little work as possible in order to get back to accepting the next request. Part of building up the `ThousandIsland.Socket` struct involves [starting the connection span in telemetry](https://github.com/mtrudel/thousand_island/blob/76c6e1c521bcd77b2e04b40d1d9d1151571f7315/lib/thousand_island/handler.ex#L353-L361), which may take an arbitrary amount of time and so is done on the handler process. 

I'll update the `When Handler Isn't Enough' docs to reflect this in the next release. Thanks for noticing!

**Comment by mtrudel** [comment]
Note also that you can call `ThousandIsland.Socket.recv` calls anywhere, including within a `handle_data` call. This is actually closer to the typical use case, and is eg how Bandit reads request bodies of arbitrary size

**Comment by sthompson-crestron** [comment]
@mtrudel  Thank you.  I will look at the implementation in Bandit as an example.  

It might be interesting to add something like Apple's `NWProtocolFramer` to ThousandIsland.  Basically it's a mechanism that lets you define a way that "messages" are framed (incoming and outgoing) on the underlying TCP socket and then instead of `handle_data` you'd have a handler that gets `handle_message` which would just contain the payload with all the framing removed.  It would probably have to be some kind of different Handler.

Maybe that doesn't match the goals of ThousandIsland, but writing this same code in Swift it made handling the framing portions of our protocol very convenient.

**Comment by mtrudel** [comment]
I've currently got that work slotted in about three or four bundles down my list, so likely a late 2024/ early 2025 thing

**Comment by sthompson-crestron** [comment]
Cool  I will look forward to it.  If you need a test case, let me know.  

As I understand it, that's how Apple's `Network.framework` handles Web Sockets too - it's just a framing handler as you suggest.
