### ISSUE TITLE
Process isolation between requests

### ISSUE THREAD

**Issue by derekkraan** [mtrudel/thousand_island#43]
Hi @mtrudel, I was working today and I noticed a weird thing. I was subscribing to a Phoenix.PubSub in my LiveView mount function. But on the first message (only), I was seeing an error message in the console, that `Bandit.HTTP1.Handler` was dying because it didn't implement a `handle_info/2` callback that handled my message.

So I did some digging, turned out I forgot to do `if connected?(socket), do: subscribe()`, so that fixed the issue for me.

But then I got to thinking: what is really happening here? Are my controller actions being run in the same process as the socket connection handling? So I ran a test, and put the following code at the top of a controller action:

```elixir
val = Process.get(:testing, 0) |> IO.inspect(label: "Requests served by this process")
Process.put(:testing, val + 1)
```

And sure enough, in my logs, `Requests served by this process: 6` appeared pretty quickly.

I ran the same test using cowboy (different version of phoenix though, admittedly), and got the expected `0` every time.

So I guess I am wondering if this is an issue. Is there a class of bugs that will be hard to find because of this approach? Will it  encourage users to use the Process dict, by making it persist between requests?

And what are the performance implications of encapsulating single requests in their own process?

Or is the answer simply "don't do anything weird and everything will be ok"?

_edit: these processes might end up doing a lot more GC than normal. The advantage of encapsulating requests in processes is that the BEAM can just toss everything when the process ends. If we do it this way, re-using processes, then we'll be forcing the BEAM to GC anything we are doing in our processes. Not sure how this shakes out in benchmarks._

**Comment by derekkraan** [comment]
After reading the docs more carefully, and doing some more testing, it appears that this only happens when my connection is kept alive (by the browser in this case).

**Comment by derekkraan** [comment]
I'm going to close this. I don't think there is an "issue" here, just my rambling now at this point.

I am very tempted now to do things like authenticate a user once and then stuff something into the pdict :P

**Comment by mtrudel** [comment]
Part of the HTTP/1 connection concept is the notion of keepalives. Specifically, one TCP connection from client to server can be used for any number of HTTP requests, by keeping the connection open after a request has completed and simply sending a new request down the TCP connection. (This doesn't allow multiple requests to be live simultaneously on the same connection, note). 

I believe Cowboy spins up a new process per request, which is the primary contributor to it having two processes per HTTP request (one process for the connection, one for the request). We follow a similar model for HTTP/2 out of necessity, but within HTTP/1 we optimize this flow by doing all of the work for (possibly multiple) requests within the single connection process. This is *very* much by design & intentional. Sharing a process dict between subsequent requests is an unfortunate side effect, but it's also pretty deep in the weeds.

You can see this made real here: https://github.com/mtrudel/bandit/blob/main/lib/bandit/http1/handler.ex#L25

In fact, the original project that spawned Bandit & Thousand Island in the first place uses Process dicts between subsequent requests. Being able to do this was actually one of the main reasons I wrote the stack in the first place :) See https://github.com/mtrudel/hap/blob/main/lib/hap/hap_session_transport.ex#L98 for details.

**Comment by mtrudel** [comment]
Regarding your point about authenticating once & stuffing things in the process dictionary, I wouldn't do that :). To the extent that HTTP/1 Bandit connections *do* share a process dict, that's the only server / protocol combination that does. It's an implementation detail that you ought not to rely on, and it's certainly not something that's part of Bandit's public API. 

Where it *is* useful is in places like HAP (linked above) where maintaining state on the connection as a whole is necessary.

**Comment by derekkraan** [comment]
Thanks for taking the time to respond. I'll try to resist the temptation haha.

**Comment by derekkraan** [comment]
I just came across [the Ecto docs](https://hexdocs.pm/ecto/multi-tenancy-with-foreign-keys.html) which are encouraging users to do exactly this (stuff user_id into the process dictionary for use later).
