### ISSUE TITLE
FunctionClauseError randomly happens

### ISSUE THREAD

**Issue by pvthuyen** [mtrudel/thousand_island#83]
We've been recently trying to use `Bandit` and `thousand_island` for our services and have received some FunctionClauseError issues on Sentry. I've attached a screenshot with the stacktrace here.

<img width="1896" alt="Screenshot 2023-08-30 at 1 45 35 PM" src="https://github.com/mtrudel/thousand_island/assets/7485121/3a5fd7d8-333f-4349-963d-d182ce0de795">

**Comment by mtrudel** [comment]
This is cut from the same essential cloth as https://github.com/mtrudel/bandit/issues/218, https://github.com/mtrudel/bandit/issues/141, and https://github.com/mtrudel/bandit/issues/84. You aren't able to send messages to HTTP handler processes because Plug provides no way to surface them up to your application code.

**Comment by mtrudel** [comment]
Closing for hygiene. If the above pointers do NOT in fact answer the issue, please feel free to reopen!

Thanks for the issue!
